[build]
    # Set the folder where Netlify should look for your serverless functions.
    functions = "netlify"

[[redirects]]
    # This is a good standard practice for Single Page Applications (SPAs)
    # and ensures all paths resolve correctly.
    from = "/*"
    to = "/index.html"
    status = 200
