[build]
    # Set the folder where Netlify should look for your serverless functions.
    functions = "netlify"

[functions]
    # Configure the runtime settings for Node.js functions
    node_bundler = "zisi"
    node_bundler_version = "v8"
